# Generated by Django 3.1.4 on 2021-01-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='album',
            name='available',
        ),
        migrations.RemoveField(
            model_name='album',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='album',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='album',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='album',
            name='title',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='contacted',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
    ]
